version: "3.8"

services:
  server:
    image: yaibawiliam/kie_server:v3.1.5
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1200000000
    environment:
      NUMBER_OF_INSTANCES: 1
    deploy:
      replicas: 1
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: 'NVIDIA-GPU'
                value: 0
          # devices:
          #   - driver: nvidia
          #     device_ids: ['0']
          #     capabilities: [gpu]
    networks:
      - network1

  client:
    image: yaibawiliam/kie_client:v1.1.10
    # container_name: kie_client # not support
    # depends_on:
    #   - kie_server
    environment:
      IP_DEST: kie_server
    ports:
      - "5003:5003"
    networks:
      - network1

networks:
  network1: