services:
  kie_server:
    image: yaibawiliam/kie_server:v3.0.9
    container_name: kie_server
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - /home/yaiba/project/KIE/server/log:/venv/log
    shm_size: "1gb"
    deploy:
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: 'NVIDIA-GPU'
                value: 0
          # devices:
          # - driver: nvidia
          #   device_ids: ['0']
          #   capabilities: [gpu]

  kie_client:
    image: yaibawiliam/kie_client:v1.0
    container_name: kie_client
    depends_on:
      - kie_server
    # environment:
    #   DATABASE_HOST: kie_client
    ports:
      - "5000:5000"
